[platformio]
default_envs = esp32-c5
build_cache_dir = .pio/buildcache
cache_dir = .pio/cache
boards_dir = boards

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
platform_packages =
    framework-arduinoespressif32-libs @ https://github.com/bmorcelli/esp32-arduino-lib-builder/releases/download/idf-release_v5.5/bruce_esp32-arduino-libs-20260123-153546.zip

monitor_filters = esp32_exception_decoder, send_on_enter, colorize
framework = arduino
monitor_speed = 115200

[env:esp32-c5]
extends = env
board = esp32-c5-devkitc-1
board_build.mcu = esp32c5
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 4MB

build_flags =
    -Os
    -Wl,--gc-sections
    -DCORE=1
    -DSERIAL_PRINTING=1
    -DWEB_DASHBOARD=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCONFIG_IDF_TARGET_ESP32C5
    -DRISCV

lib_deps =
    bblanchon/ArduinoJson@^6.21.5

build_src_filter = +<*> -<.git/> -<.svn/>
